spring:
  application:
    name: demo
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kgh?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
custom:
  file:
   dir: C:/kgh/upload

payment:
  toss:
    test_client_api_key : test_ck_EP59LybZ8BKvwNzyLRkW36GYo7pR
    test_secrete_api_key : test_sk_oEjb0gm23PY9MXL026DkVpGwBJn5
    success_url : "http://localhost:8080/api/v1/payment/toss/success"
    fail_url : "http://localhost:8080/api/v1/payment/toss/fail"